name: "Terraform"

on:
  push:

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Init Terraform
        run: terraform init

      - name: Plan
        run: |
          terraform plan -out tfplan

      - name: Debug
        run: |
          echo ${{ steps.plan.outputs.stdout }}
